In [1]:
import numpy as np

In [2]:
my_list=[10,20,30,40]


In [3]:
type(my_list)

list

In [4]:
np.array(my_list)

array([10, 20, 30, 40])

In [5]:
my_numpy_array=np.array(my_list)

In [6]:
type(my_numpy_array)

numpy.ndarray

In [7]:
my_numpy_array.max()

40

In [8]:
np.ones(5)


array([1., 1., 1., 1., 1.])

In [9]:
np.zeros(4)

array([0., 0., 0., 0.])

In [10]:
np.random.random(4)

array([0.75753707, 0.57124756, 0.63461386, 0.94758742])

In [11]:
#array  aritmethic

In [12]:
list1=[1,2,3]
list2=[4,5,6]
list1+list2

[1, 2, 3, 4, 5, 6]

In [13]:
np_array1=np.array(list1)
np_array2=np.array(list2)
np_array1+np_array2

array([5, 7, 9])

In [14]:
np_array1 *np_array2

array([ 4, 10, 18])

In [15]:
list1 * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [16]:
np_array1 *5

array([ 5, 10, 15])

In [32]:
#arrange and indexing

In [18]:
list(range(0,10))


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [26]:
np_array=np.arange(0,10)


In [27]:
np_array[0]

0

In [28]:
np_array[-1]

9

In [29]:
np_array[1:4:]

array([1, 2, 3])

In [30]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [31]:
# Numpy Matrices

In [35]:
matrix=[[5,10],[15,20]]


In [36]:
matrix[1]

[15, 20]

In [37]:
matrix[0]

[5, 10]

In [39]:
matrix[0][1]

10

In [41]:
np_matrix=np.array([[5,10],[15,20]])
np_matrix

array([[ 5, 10],
       [15, 20]])

In [42]:
np_matrix[1][0]

15

In [48]:
np_matrix.sum()

50

In [44]:
np.ones(3)

array([1., 1., 1.])

In [45]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [46]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
first_array=np.array([[10,20],[30,40]])
second_array=np.array([[5,15],[25,35]])
first_array+second_array


array([[15, 35],
       [55, 75]])

In [50]:
third_array=np.array([[50,60]])
first_array+third_array

array([[ 60,  80],
       [ 80, 100]])

In [51]:
fourth_array=np.array([[10,20,30]])
first_array+fourth_array

ValueError: operands could not be broadcast together with shapes (2,2) (1,3) 

In [52]:
# Matrix multiplication

In [53]:
first_array


array([[10, 20],
       [30, 40]])

In [54]:
second_array

array([[ 5, 15],
       [25, 35]])

In [56]:
first_array*second_array # bu matrix çarpımı değildir

array([[  50,  300],
       [ 750, 1400]])

In [57]:
# dot product


In [70]:
'''1,2,3   1,10
 (1*3)     100,10000
           10000,100000     sonuc= (1*2)
              (3*2)'''

'1,2,3   1,10\n (1*3)     100,10000\n           10000,100000     sonuc= (1*2)\n              (3*2)'

In [60]:
first_matrix=np.array([[10,20,30]])

In [61]:
first_matrix.shape

(1, 3)

In [62]:
sec_matrix=np.array([[2,3],[2,3],[2,3]])

In [63]:
sec_matrix.shape

(3, 2)

In [69]:
#first_matrix * sec_matrix yapılamaz

In [65]:
 result_matrix=first_matrix.dot(sec_matrix)

In [66]:
result_matrix

array([[120, 180]])

In [67]:
result_matrix.shape

(1, 2)

In [71]:
#numpy operations


In [72]:
array=np.random.randint(1,100,20)

In [73]:
array

array([78, 36, 67, 37, 20, 76, 25, 17, 87, 18, 31, 55, 41, 62,  2, 73, 21,
       20, 14,  8])

In [76]:
array > 25

array([ True,  True,  True,  True, False,  True, False, False,  True,
       False,  True,  True,  True,  True, False,  True, False, False,
       False, False])

In [78]:
array [ array > 25]

array([78, 36, 67, 37, 76, 87, 31, 55, 41, 62, 73])

In [79]:
#transpose & reshape

In [80]:
matrix_array=np.array([[10,20],[20,30],[30,40]])
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [82]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [84]:
random=np.random.random((6,1))
random

array([[0.39594289],
       [0.31440654],
       [0.0123956 ],
       [0.50965303],
       [0.00431371],
       [0.03386875]])

In [85]:
random.reshape(2,3)

array([[0.39594289, 0.31440654, 0.0123956 ],
       [0.50965303, 0.00431371, 0.03386875]])

In [86]:
# z-score


In [88]:
data=np.array([10,12,13,15,18,25,100,105])
#outlier: aykırı değerler 100-105

In [90]:
mean=np.mean(data)
mean

37.25

In [91]:
std=np.std(data)
std

37.9333296719389

In [93]:
z_score= (data- mean)/std
z_score

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [94]:
#outlierların 1 den büyük olduğu yerler outlierlar

In [96]:
data[z_score <1]

array([10, 12, 13, 15, 18, 25])

In [98]:
#math equations
# 2x + 3y = 8 and 5x + 7y = 19

#coefficient : katsayılar
A=np.array([[2,3],[5,7]])

#constant: sabitler
b=np.array([8,19])

solution=np.linalg.solve(A,b)
solution

array([1., 2.])